### ISSUE TITLE
Not sending any message

### ISSUE THREAD

**Issue by danilogkir** [baklysystems/laravel-chat-messenger#12]
My last issue described a problem with the PHP code because of the versions.

But after deleting those lines including `count` i accessed the page and yes, i added the `yields` and besides that i tried to send a message, but clicking the button of "send" it does not do anything.

Hope to get an answer soon, thanks.

**Comment by elbakly** [comment]
For the count issue, if I have some extra time to night, I will fix it to support different version of php. as for the send not sending if you can please share more debug info i.e: console.log from your browser .

mean while my first guess would be : 

@yield('js-scripts')
make sure you load Jquery
check your pusher keys in config/messenger.php

**Comment by ghost** [comment]
Hello @elbakly,

The keys work and they identify that the user are active. I mean, it actually works.

But the thing is that i added @yield('js-scripts') to the `app.blade.php` and also de `css` ones. 

Jquery is also being loaded, but give me a second to show you the console of inspect element.

**Comment by ghost** [comment]
Cool, now it works, also i forgot to add the jquery (lol).

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>`

It would be cool if that piece of code is just added on `@yield('js-scripts')`, i mean, easier and to avoid user confusion also... you know, there is people that do not read the documentation, they just jump into it.

Cheers @elbakly, nice package!

**Comment by elbakly** [comment]
@danilogkir  Great I hope you enjoy it,

adding the jquery has to be done by the user a we don't know if he already have this in his existing setup and if he is using a specific version for any purpose, so this will let them add it knowingly
